### ISSUE TITLE
Active Tab Does Not Always Highlight

### ISSUE THREAD

**Issue by Swivelgames** [Swivelgames/apex-adapt-dark-slim-ui#2]
Initially pointed out by @oscarmcm, the active tab does not always highlight.

![image](https://user-images.githubusercontent.com/2553459/30005168-a7f1a62a-9099-11e7-87b8-8498196f827c.png)

The issue has been resolved @ v0.4.1

@oscarmcm, can you confirm this issue no longer occurs?

**Comment by oscarmcm** [comment]
@Swivelgames Yup it works like a charm now, I don't know if an option exist for it but active tab border color is on bottom, as you can see on Apex UI Slim there's on top
![image](https://user-images.githubusercontent.com/2553459/30072189-c6c0f39c-9226-11e7-8996-95ffaabef66f.png)

**Comment by Swivelgames** [comment]
@oscarmcm Good catch! I may be able to look into an option to allow the border to be on top.

Thanks for confirming this is fixed! :)
