### ISSUE TITLE
Line number background-color

### ISSUE THREAD

**Issue by oscarmcm** [Swivelgames/apex-adapt-dark-slim-ui#3]
Its an screen shot from apex, as you can see background color in line number is the same as background color from editor.
![image](https://user-images.githubusercontent.com/2553459/30073630-c0738a5e-922b-11e7-9f02-179c7147ad55.png)

But with apex-adapt-dark-slim-ui background color is a little bit different 
![image](https://user-images.githubusercontent.com/2553459/30073728-2f777db6-922c-11e7-8304-e91d014ff371.png)

I think it comes from Base Atom theme, maybe you can use the same color

**Comment by Swivelgames** [comment]
Especially since this is mainly based on Apex and the simplicity of its design, I certainly agree that the gutter should be the same as the editor background.

I've just fixed this in `v0.4.2`. Please update :)
