### ISSUE TITLE
Syntax theme

### ISSUE THREAD

**Issue by ovidius72** [Swivelgames/apex-adapt-dark-slim-ui#5]
Can you please tell us what is the syntax theme used in the screenshot ?
Thanks.

**Comment by Swivelgames** [comment]
Hey @ovidius72!

I usually sport one of the **_DuoTone syntax themes_**.

The one in the `README.md` screenshot is called [**DuoTone Dark Amethyst**](https://atom.io/themes/duotone-dark-amethyst-syntax) by [bynines](https://atom.io/users/bynines).

![Apex Adapt Dark Slim UI](https://user-images.githubusercontent.com/1456302/29089518-1df0638c-7c42-11e7-9ceb-55f15a15b265.png)

[**Check out `duotone-dark-amethyst-syntax` on Atom.io**](https://atom.io/themes/duotone-dark-amethyst-syntax)

**Comment by ovidius72** [comment]
thanks
